stages:
  - build
  - deploy

make_image:
  tags:
    - team6
    - shell
  stage: build
  script:
    - docker build --no-cache -t ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} .
    - mkdir image
    - docker save ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} > image/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}.tar
  artifacts:
    paths:
      - image

deploy:
  tags:
    - team6
    - shell
  stage: deploy

  script:
    - docker load -i image/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}.tar
    - docker tag ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}
    - docker tag "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}" "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
    - docker tag ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}
