stages:
  - test
  - build
  - deploy

test:
  image: golang:1.18
  tags:
    - team6
    - docker
  stage: test
  script:
      - go install github.com/t-yuki/gocover-cobertura@latest
      - go install github.com/jstemmer/go-junit-report@latest
      - CGO_ENABLED=0 go test -v -coverprofile=coverage.txt -covermode count ./... > junit.txt
      - go tool cover -func coverage.txt # for gitlab to calculate coverage
      - go-junit-report < junit.txt > junit.xml
      - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      cobertura: coverage.xml
      junit: junit.xml

make_image:
  tags:
    - team6
    - shell
  stage: build
  script:
    - docker build --no-cache -t ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} .
    - mkdir image
    - docker save ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} > image/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}.tar
  artifacts:
    paths:
      - image

deploy:
  tags:
    - team6
    - shell
  stage: deploy

  script:
    - docker load -i image/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}.tar
    - docker tag ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}
    - docker tag "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}" "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
    - docker tag ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID} ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}
